<?php
/**
 * ExtIntLinnworksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ExtIntLinnworksTest Class Doc Comment
 *
 * @category    Class
 * @description ExtIntLinnworks
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExtIntLinnworksTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ExtIntLinnworks"
     */
    public function testExtIntLinnworks()
    {
    }

    /**
     * Test attribute "linnworks_unique_identifier"
     */
    public function testPropertyLinnworksUniqueIdentifier()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {
    }

    /**
     * Test attribute "vat_number"
     */
    public function testPropertyVatNumber()
    {
    }

    /**
     * Test attribute "eori_number"
     */
    public function testPropertyEoriNumber()
    {
    }

    /**
     * Test attribute "ioss_number"
     */
    public function testPropertyIossNumber()
    {
    }

    /**
     * Test attribute "default_weight"
     */
    public function testPropertyDefaultWeight()
    {
    }

    /**
     * Test attribute "default_length"
     */
    public function testPropertyDefaultLength()
    {
    }

    /**
     * Test attribute "default_width"
     */
    public function testPropertyDefaultWidth()
    {
    }

    /**
     * Test attribute "default_height"
     */
    public function testPropertyDefaultHeight()
    {
    }

    /**
     * Test attribute "default_consignee_phone"
     */
    public function testPropertyDefaultConsigneePhone()
    {
    }

    /**
     * Test attribute "default_consignee_email"
     */
    public function testPropertyDefaultConsigneeEmail()
    {
    }
}
